### ISSUE TITLE
fastify server binding lost in Route handlers

### ISSUE THREAD

**Issue by grommett** [seriousme/fastify-openapi-glue#169]
Calling `this` in a route handler refers to the `service` object instead of `fastify`. This causes lost references to `fastify` and possibly other plugins attached to the `fastify` object. It may have been broken in #73 

For example, when used with fastify-mongo:

```js
fastify.get('/user/:id', function (req, reply) {
  const db = this.mongo.db // throws because fastify.mongo no longer exists
  ...
})
```
From Fastify docs:
> `handler(request, reply)`: the function that will handle this request. **The Fastify server will be bound to `this`** when the handler is called. Note: using an arrow function will break the binding of this.

I'm working around this by adding `fastify` back to the service object, but it may cause confusion for other users (as it did for me) when installing this plugin and following along with the docs.
```js
const options = {
  specification: 'swagger.yaml',
  prefix: 'v1',
  noAdditional: true,
  service: () => ({
    fastify: app,
    handleRequest
  }),
};
```

Possible solutions:
1. Document the scope change and workaround
2. Bind routes with both `service` and `fastify`:

If this is where it's happening, something like:
```js
async function generateRoutes(routesInstance, opts) {
    config.routes.forEach(item => {
      const response = item.schema.response;
      if (response) {
        stripResponseFormats(response);
      }
      if (service[item.operationId]) {
        routesInstance.log.debug("service has", item.operationId);
        item.handler = service[item.operationId].bind({...service, ...routeInstance}); // maybe? not sure if routeInstance is the fastify instance
      } else {
        item.handler = async (request, reply) => {
          throw new Error(`Operation ${item.operationId} not implemented`);
        };
      }
      routesInstance.route(item);
    });
  }
```

If I'm not missing something, and this is indeed an issue, I'll gladly create a PR.

**Comment by seriousme** [comment]
Thanks for the feedback.

The binding to service.js was indeed purposely created in #73. The idea being that Fastify is "just" a webserver and any service integrations should be done within your service.

E.g. you should be able to test your service without Fastify. That pattern would be broken if you also link your backend service to Fastify again.

I'm a bit hesitative to add both objects to the scope as this could lead to strange errors if Fastify decides to use method names that overlap with current users service definitions.

I'll have a look into improving the documentation on this subject.

Kind regards,
Hans

**Comment by grommett** [comment]
> ...any service integrations should be done within your service.

Ok,  yeah that makes sense. Thanks for the feedback. Since this is intentional I'll close this issue.

**Comment by seriousme** [comment]
FYI:  

I have updated the README to clarify this topic better and added [docs/bindings.md](https://github.com/seriousme/fastify-openapi-glue/blob/master/docs/bindings.md)

Thanks again for highlighting this and apologies for any inconvenience caused !

Kind regards,
Hans

**Comment by grommett** [comment]
That looks great, Hans! Thanks for the update. Appreciate your explanation and documentation.

Best,
David
