### ISSUE TITLE
Generate TypeScript types for each operation's params and response

### ISSUE THREAD

**Issue by rattrayalex** [seriousme/fastify-openapi-glue#201]
It would be useful to generate TypeScript somewhat like this (based on what I see in [this example](https://github.com/seriousme/fastify-openapi-glue/blob/master/examples/generatedProject/service.js)):

```ts
type AddPetParams = {
  id?: number,
  category?: {id?: number, name?: string},
  /** @example "doggie" */
  name: string,
  photoUrls: []string,
  tags?: []{id?: number, name?: string},
  status?: 'available' | 'pending' | 'sold',
}

type Pet = {
  //...
}

async addPet(req: Req<AddPetParams>): Pet {
  console.log("addPet", req.params);
  return { name: "doggie", photoUrls: [] };
}
```

**Comment by seriousme** [comment]
Nice idea :-)

- [X] Json-schema to TypeScript is possible. 
- [ ] OpenAPI defines a few types on top of Json-schema so we would need to cater for those as well.  
- [ ] `Req` and `Res` are existing Fastify types, so we would need to extend those.
- [X] the generator would need some extra template for Typescript, but thats doable

As you might have noticed in #171 I'm planning to migrate to ESM by May (few weeks time ;-)) so my suggestion would be try to add this functionality to the [migrate-to-esm](seriousme/fastify-openapi-glue/tree/migrate-to-esm) branch.

I will do some research ;-)

Thanks again for the idea !

Hans

**Comment by rattrayalex** [comment]
Awesome!

If it helps, [here are the types Stripe's API generates](https://github.com/stripe/stripe-node/blob/master/types/2020-08-27/Customers.d.ts) from its openapi spec (these are client-side not server-side but should be very similar). I helped build this system and would be happy to help advise if I can. I'm not using fastify yet so I may not be able to contribute code yet.

**Comment by seriousme** [comment]
Thanks for the hint.

JSONschema can get quite complex so I'd rather not build the schema-to-type converter myself ;-)
It looks like [json-schema-to-typescript](https://www.npmjs.com/package/json-schema-to-typescript) might be an option to generate types from schema. 

Now we need to find out if we can get this to work reliably with OpenApi schema extensions and the already defined fastify types.
To be continued !

**Comment by rattrayalex** [comment]
Ah, actually it looks like one can obviate this [with other tools](https://github.com/fastify/fastify/blob/main/docs/TypeScript.md), the most appealing to me being:

```ts
import {FromSchema} from 'json-schema-to-ts';

const todo = {
  type: 'object',
  properties: {
    name: { type: 'string' },
    description: { type: 'string' },
    done: { type: 'boolean' },
  },
  required: ['name'],
} as const;
type Todo = FromSchema<typeof todo>;

fastify.post<{ Body: Todo }>(
  '/todo',
  {
    schema: {
      body: todo,
      response: {
        200: todo
      },
    }
  },
  async (request, reply): Promise<Todo> => {
    request.body.name // type string
    request.body.notthere // will throw type error
    
    return await db.todos.save(request.body);
  },
);
```

Maybe your library could generate code like that? But frankly, I would personally rather write this directly anyway. So I am not sure it is worth it. 

Anyway, good luck!!

**Comment by rattrayalex** [comment]
Yes, that approach could be great too! Good luck, this seems like a great project and I hope to use it one day soon!

**Comment by seriousme** [comment]
Small update: 

I have made a prototype of the `generatedProject` in TypeScript (not automatically generated, but handmade ;-)) and that seems to work. The whole generated project (except for the tests) needs to be Typescript because else its much harder to get a coherent setup.

E.g.:

src/service.ts would then look something like:
```typescript
// implementation of the operations in the openapi specification
import { FastifyRequest, FastifyReply } from 'fastify'
import { AddPetBody } from "./service.types"

class Service {
  constructor(opts: any) { }

  // Operation: addPet
  // URL: /pet
  // summary:  Add a new pet to the store

  // valid responses
  //   '405':
  //     description: Invalid input
  //

  async addPet(req: FastifyRequest<{Body: AddPetBody}>, reply: FastifyReply) {
    console.log("addPet", req.body);
    return { key: "value" };
  }
...
}
```

and src/service.types.ts would look something like:
```typescript
import { FromSchema } from "json-schema-to-ts";

const addPetBodySchema = {
  "type": "object",
  "required": [
    "name",
    "photoUrls"
  ],
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64"
    },
    "name": {
      "type": "string",
      "example": "doggie"
    },
    "photoUrls": {
      "type": "array",
      "xml": {
        "name": "photoUrl",
        "wrapped": true
      },
      "items": {
        "type": "string"
      }
    },
    "status": {
      "type": "string",
      "description": "pet status in the store",
      "enum": [
        "available",
        "pending",
        "sold"
      ]
    }
  },
  "xml": {
    "name": "Pet"
  }
} as const;

export type AddPetBody = FromSchema<typeof addPetBodySchema>;
```

So technically it is possible to generate a TypeScript project, however it does come with some disclaimers:
-  JSON schema can get quite complex, and there is little guarantee that it will flawlessly convert to Typescript types
-  JSON schema can be based on defintions that reference eachother (e.g. the definition of `Pet` is used in multiple operations and uses definitions of `Tag` and `Category` )  json-schema-to-ts [does not support these yet](https://github.com/ThomasAribart/json-schema-to-ts/issues/13) and hence the type definitions might become rather verbose because instead of one `Pet` type each operation would now define its own `Pet` type that is most likely identical to the rest but we would not know for sure because the current parsers already dereferenced the refs. That is probably also solvable but takes more time.

**Comment by rattrayalex** [comment]
Ah, for a generated approach [`json-schema-to-typescript`](https://github.com/bcherny/json-schema-to-typescript), the one you mentioned, would probably be a better idea than [`json-schema-to-ts`](https://github.com/ThomasAribart/json-schema-to-ts), which I linked (and would make more sense for a non-generated approach). Both because it'll handle cases like that much better, and because it lets you actually see the types written out, which is much nicer.

(It's confusing they're named almost the same thing!)

**Comment by seriousme** [comment]
Well I had a look at json-schema-to-typescript and it has quite some [open issues](https://github.com/bcherny/json-schema-to-typescript/issues) as well :-(

So unless there is high demand for such a feature I'd rather wait a while until the whole ecosystem matures a bit more ;-)

Thanks again for the inspiration, I learned a lot !

Kind regards,
Hans

**Comment by rattrayalex** [comment]
Yeah, good idea – I think waiting makes sense! Hopefully people interested in the feature can upvote this issue so you can gauge interest. The issues I see on that repo makes it look like many people are happily using this in production and finding all the edge cases, so if they keep making progress it should be good to use soon.
