### ISSUE TITLE
Error: querystring must be object 

### ISSUE THREAD

**Issue by Rashad-j** [seriousme/fastify-openapi-glue#211]
I am using openapi specification to generate a new server. **I have the following settings:** 
...
/dnszone:
    get:
      tags:
      - dnszone
      summary: Searches for a certain DNS zone by nameserver name or IP address
      description: Provide Type of DNS record and Name in parameters
      operationId: dnszoneGET
      parameters:
        - $ref: '#/components/parameters/StatusDNSZoneParams'
      responses:
        "200":
...
**The value of the StatusDNSZoneParams is:** 
parameters:
    StatusDNSZoneParams:
      name: StatusDNSZoneParams
      in: query
      description: A list of params for an existing DNS zone.
      required: true
      style: form
      explode: false
      schema:
        $ref: '#/components/schemas/StatusDNSZoneRequestObj'

**When I try to call:**
curl -X 'GET' \
  'http://localhost:3000/dnszone?StatusDNSZoneParams=DNSZONE,string,EXTENDED,string' \
  -H 'accept: application/json'
I receive the error: 
{"statusCode":400,"error":"Bad Request","message":"querystring must be object"} 

**Why would this be a problem?** 

I tried to change the object serialization by changing explode to true, then tried:
curl -X 'GET' 'http://localhost:3000/dnszone?DNSZONE=string&EXTENDED=string' -H 'accept: application/json'

I get the error: 
{"statusCode":400,"error":"Bad Request","message":"querystring must have required property 'StatusDNSZoneParams'"}

Would you please explain the issue here? thanks in advance!

**Comment by seriousme** [comment]
Hi, 

According to the openAPI spec the style/explode properties are specific to RFC6570. To my knowledge Fastify does not support  RFC6570 so fastify-openapi-glue can not generate configuration data for this.  You will need to use the:
`curl -X 'GET' 'http://localhost:3000/dnszone?DNSZONE=string&EXTENDED=string' -H 'accept: application/json'`
(see also: https://stackoverflow.com/a/53171438)

More information on querystring schema in Fastify can be found at: https://www.mikulskibartosz.name/query-string-validation-in-fastify/

fastify-openapi-glue looks at the parameter and if its an 'in: query' it will add the schema of that parameter as:
```
 { 
   schema: {
       querystring: {
            <yourschema>
       }
}
```
to the path `/dnszone`
It will ignore the `style` properties as there is no way to pass this information reliably to fastify.
If you want a more visual clue on what your specification does you can use: https://editor.swagger.io/

Hope this helps. 
If not please provide a minimal (valid :-)) openApi schema that contains your problem so I can test it.

Kind regards,
Hans

**Comment by Rashad-j** [comment]
Hi Hans, 

Thanks for your reply and elaboration. I still, however, have the problem. 
Here is what I requested: 
`curl -X 'GET' \
  'http://localhost:3000/dnszone?DNSZONE=string&EXTENDED=string' \
  -H 'accept: application/json'`

and here is the server logs:
`08:39:44 ✨ incoming request GET xxx /dnszone?DNSZONE=string&EXTENDED=string
08:39:44 ✨ querystring must have required property 'StatusDNSZoneParams'`

Our openapi specification can be found [here](https://app.swaggerhub.com/apis/Rashad-j/testAPI/1.0.0)

Cheers, Rashad.

**Comment by seriousme** [comment]
Rashad,

thanks for sharing the spec.
I did a `npx fastify-openapi-glue openapi.json` based on a download of your specification.
In the generated `service.js` it says:
```
  // Operation: dnszoneGET
  // URL: /dnszone
  // summary:  Searches for a certain DNS zone by nameserver name or IP address
  // req.query
  //   type: object
  //   properties:
  //     StatusDNSZoneParams:
  //       required:
  //         - DNSZONE
  //       type: object
  //       properties:
  //         DNSZONE:
  //           type: string
  //           description: Name of the zone to be queried
  //         EXTENDED:
  //           type: string
  //           description: Switch to return EXTENDED properties, for URL / EMAIL forwardings
  //       description: A list of params for an existing DNS zone.
  //   required:
  //     - StatusDNSZoneParams
  //
  // valid responses
  //   '200':
  //     description: Command completed successfully
  //     content:
  //       application/json:
  //         schema:
  //           type: object
  //           properties:
  //             success:
  //               type: string
  //               description: success message
  //           example:
  //             success: success message
  //   '420':
  //     description: Command failed due to server error. Server closing connection
  //     content:
  //       application/json:
  //         schema:
  //           type: object
  //           properties:
  //             error:
  //               type: string
  //               description: error message
  //           example:
  //             error: 420 error
  //   '421':
  //     description: Command failed due to server error. Client should try again
  //     content:
  //       application/json:
  //         schema:
  //           type: object
  //           properties:
  //             error:
  //               type: string
  //               description: error message
  //           example:
  //             error: 421 error
  //
```
What happens is that fastify-openapi-glue is not aware of the rules around `explode=true` for which the openapi specification [says](https://spec.openapis.org/oas/v3.1.0#style-values):
`When this is true, parameter values of type array or object generate separate parameters for each value of the array or key-value pair of the map. For other types of parameters this property has no effect. When style is form, the default value is true. For all other styles, the default value is false.`

So thats why it keeps the toplevel `StatusDNSZoneParams` in place.

Simple workaround is to create separate parameters. An example of that can be found at: https://github.com/seriousme/fastify-openapi-glue/blob/master/examples/petstore/petstore-openapi.v3.json#L628

Kind regards,
Hans

**Comment by seriousme** [comment]
FYI:  I have just added support for querystring objects in #212.

This should solve your use case without having to rewrite your schema.

Kind regards,
Hans

**Comment by seriousme** [comment]
Just released v2.5.0 that contains this fix to NPM.

Enjoy,
Hans

**Comment by Rashad-j** [comment]
Thank you, it does not complain about objects now, still, it cannot find the params in the request. See below the server logs:
```
08:53:58 ✨ Server listening at http://127.0.0.1:3000
08:54:42 ✨ incoming request GET xxx /dnszone?DNSZONE=string&EXTENDED=string
dnszoneGET {}
08:54:42 ✨ request completed 7ms
08:55:09 ✨ incoming request PUT xxx /dnszone?DNSZONE=string&SOATTL=string&SOAMNAME=string
dnszonePUT {}
08:55:09 ✨ request completed 1ms
08:55:35 ✨ incoming request DELETE xxx /dnszone/asd
dnszoneDnszoneDELETE { dnszone: 'asd' }
08:55:35 ✨ request completed 2ms
```
`GET` and `PUT` receive in query objects, whereas `DELETE` received in path param.

**Comment by Rashad-j** [comment]
I've accessed the params via `req.query`. Closing this issue now, thank you!
