### ISSUE TITLE
Swagger Docs not showing when using openapi-glue routes.

### ISSUE THREAD

**Issue by Rikihanks** [seriousme/fastify-openapi-glue#247]
Hello! I have defined my routes in an openapi v2 json that looks something like this 
`{
  "swagger": "2.0",
  "info": {
  "title": "Posts API",
  "description": "Post swagger definition for fastify",
  "termsOfService": "http://swagger.io/terms/",
  "contact": {
    "name": "API Support",
    "url": "http://www.swagger.io/support",
    "email": "support@swagger.io"
  },
  "license": {
    "name": "Apache 2.0",
    "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
  },
  "version": "2"
  },
  "tags":[
    {
      "name": "posts",
      "description":"Posts"
    }
    ],
  "schemes": ["http"],
  "paths": {
    "/": {
      "get": {
        "summary": "Returns array with all posts",
        "description": "",
        "operationId": "getAllPosts",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Post"
              }
            }
          }
        }
      }
    },
    "/add": {
      "post": {
        "summary": "Creates a new post",
        "description": "",
        "operationId": "createPost",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "responses": {
          "201": {
            "description": "created",
            "schema": {
               "$ref": "#/definitions/Post"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Post": {
      "type": "object",
      "required": ["id", "user", "title"],
      "properties": {
        "id": {
          "type": "string"
        },
        "user": {
         "type": "string"
        },
        "title": {
          "type": "string",
          "example": "titulo de ejemplo"
        }
      },
      "xml": {
        "name": "Post"
      }
    }
  }
}`

The problem is that my instance of swagger is not showing in the docs the paths  that I created. (They work fine in code, they are being called sucessfully from postman / insomnia) but there is no way to see them on the swagger instance.
Its worth noting that when I create and register a route manually it is shown correctly on the swagger docs.

This is my config:

`void fastify.register(openapiGlue, {
    specification: openapiJson.default,
    service: new Service(),
    prefix: "v1",
    noAdditional: true,
    ajvOptions: {
      formats: {
        "custom-format": /\d{2}-\d{4}/
      }
    }
  })`

`void fastify.register(swagger, {
    routePrefix: "/docs",
    swagger: {
      info: {
        title: "Test swagger",
        description: "Testing the Fastify swagger API",
        version: "0.1.0",
      },
      externalDocs: {
        url: "https://swagger.io",
        description: "Find more info here",
      },
      host: "localhost",
      schemes: ["http"],
      consumes: ["application/json"],
      produces: ["application/json"],
    },
    uiConfig: {
      docExpansion: "full",
      deepLinking: false,
    },
    staticCSP: true,
    transformStaticCSP: (header) => header,
    exposeRoute: true,
  });`

**Comment by seriousme** [comment]
Hi,

thanks for asking.

In fastify plugins are isolated from their neighbors through encapsulation:

> register creates a new Fastify context, which means that if you perform any changes on the Fastify instance, those changes will not be reflected in the context's ancestors. In other words, encapsulation!

https://www.fastify.io/docs/latest/Plugins-Guide/#register
So fastify-swagger can't see the routes created by fastify-openapi-glue.

A solution is to use `static mode` on fastify-swagger, see:
https://github.com/fastify/fastify-swagger#static
You already have your specification in `openapiJson.default`, so if you pass that to fastify-swagger it should work :-)

Kind regards,
Hans

**Comment by Rikihanks** [comment]
Aye, bless you good man!
