### ISSUE TITLE
Any reason why AJV isn't passed in as an argument?

### ISSUE THREAD

**Issue by stuft2** [seriousme/fastify-openapi-glue#303]
Passing an AJV instance into this plugin would result in fewer direct dependencies for this package and more customizability from a user's perspective. Not everyone needs the extra ajv format options so they could optimize their code by not including it or by only including the extra formats that they need.

**Comment by seriousme** [comment]
Well initially ajv-formats was part of AJV, and not having to pass an AJV instance simplified usage.
Pulling it out now would be a semver Major, maybe I´ll change the interface when fastify 4 comes and people have to move anyway ;-)

Hope this answers your question.

Kind regards,
Hans

**Comment by stuft2** [comment]
Yes, that sounds reasonable. Thanks for the quick answer.
