### ISSUE TITLE
Model composition using allOf doesn't work

### ISSUE THREAD

**Issue by ashutoshgngwr** [seriousme/fastify-openapi-glue#31]
The following schema break application without giving any errors or warnings

    components:
      schemas:
        baseUser:
          type: "object"
          properties:
            username:
              type: "string"
            email:
              type: "string"
              format: "email"
            is_verified:
              type: "boolean"

        newUser:
          allOf:
            - type: "object"
              properties:
                password:
                  type: "string"
            - $ref: "#/components/schemas/baseUser"

Application starts working fine if `allOf` is removed or if there is only a sinlge sub-schema under `allOf`.
I am using `fastify-openapi-glue` as a middleware to Fastify server.

**Comment by ashutoshgngwr** [comment]
After digging through the source, it turns out `fastify-openapi-glue` was assigning type `undefined` to `newUser` since it is literally undefined in schema. :man_facepalming:

Closing the issue.!

**Comment by simo-eskalera** [comment]
Thanks for the tip @ashutoshgngwr. It worked!
It would be nice to not hide the validation errors in the catch block so that we can quickly identify what needs fixing:
https://github.com/seriousme/fastify-openapi-glue/blob/master/lib/parser.js#L35

**Comment by seriousme** [comment]
I just checked and the message I got from swagger-parser is:
```
[object Object] is not a valid Openapi API definition
```
Can you explain what how that would be more descriptive than:
```
'specification' parameter must contain a valid version 2.0 or 3.0.x specification
```
Both say that you need to use another tool (e.g. https://editor.swagger.io) to find the exact error.
The current error explains which parameter caused the error whereas the swagger-parser error obviously can't help with that.

But maybe I'm overlooking something, so please feel free to discuss.

Kind regards,
Hans

**Comment by ashutoshgngwr** [comment]
@seriousme JSON schema for OAS v3 should be released soon. See [this pull request](https://github.com/OAI/OpenAPI-Specification/pull/1744).

If we can use JSON schema with AJV to validate specification, we may get better error messages and also get rid of `swagger-parser` altogether.

_Cheers_
