### ISSUE TITLE
Inconsistencies with validation and additional properties

### ISSUE THREAD

**Issue by kratoskat** [seriousme/fastify-openapi-glue#338]
Hey,

I've recently noticed that the Request body schema validation isnt working as expected (at least for me).

Additional properties are going through as opposed to being ignored and the noAdditional prop doesnt have any effect in my code.
Type validation isnt working either - i can pass whatever value i want to my properties and it will completely ignore them.

I'm on the latest version

i will be adding an example/replication as soon as i'm able to tomorrow but just wanted to post this just in case it's a known issue.

**Comment by seriousme** [comment]
Hi, 

thanks for the heads up.
It should (dangerous word here ;-)) work ok since the test suite explicitly tests for it:

https://github.com/seriousme/fastify-openapi-glue/blob/0328bb853121901615fb8fe102c2a50dc73a2f8b/test/test-plugin.v3.js#L77-L81

and then:

https://github.com/seriousme/fastify-openapi-glue/blob/0328bb853121901615fb8fe102c2a50dc73a2f8b/test/test-plugin.v3.js#L231-L250

Happy to look into this if you can provide an example that takes a wrong turn.

Kind regards,
Hans

**Comment by kratoskat** [comment]
Hey! thanks for the fast reply - just pull down your code and went through the test cases.

The noAdditional option wasnt working because i hadn't defined "additionalProperties": false in my spec so it wasnt able to enforce anything. Definitely my bad.

In regards to Type validation, i assumed if it'd defined a body/query param as string and then passed a number it would throw an error. Am i wrong in assuming that? Is type there just to describe the params?

**Comment by seriousme** [comment]
Hi,

good question :-)

AJV by default does [not coerce types](https://ajv.js.org/options.html#coercetypes).
However to make life a little easier `fastify-openapi-glue` will set a set of 'sensible defaults', including `coerceTypes: true`
https://github.com/seriousme/fastify-openapi-glue/blob/f60a9631b3512c6ce492f0785ceeb499ef006920/index.js#L49-L54

If you want to override this behaviour you can pass your own [ajvOptions](https://github.com/seriousme/fastify-openapi-glue#options).

Hope this helps !

Kind regards,
Hans

**Comment by kratoskat** [comment]
Amazing, never worked with AJV so will check it out! You've been an awesome tool btw, thanks for making life easier for us haha!

And sorry for the false postive! i'll close this now
