### ISSUE TITLE
Wrong dynamic import in UPGRADING.md

### ISSUE THREAD

**Issue by WIStudent** [seriousme/fastify-openapi-glue#348]
To get the default export from a dynamic import you need to use
```js
const {default: openapiGlue} = await import('fastify-openapi-glue');
```
instead of 
```js
const openapiGlue = await import("fastify-openapi-glue");
```

**Comment by seriousme** [comment]
Hi,

thanks for raising the issue !

I just fixed it so you can still use: `const openapiGlue = await import("fastify-openapi-glue");`
I also added tests to prevent regression.

Released as [3.0.1](https://github.com/seriousme/fastify-openapi-glue/releases/tag/v3.0.1)

Thanks again,
Hans
