### ISSUE TITLE
SecurityHandler overrides error

### ISSUE THREAD

**Issue by trycoon** [seriousme/fastify-openapi-glue#357]
Hi!
If I throw an error within the securityhandler, like this:

      throw new ForbiddenError('User don't have permission to requested resource');
      throw new InternalServerError('Technical error, please try again later');
      
Its caught here https://github.com/seriousme/fastify-openapi-glue/blob/master/lib/securityHandlers.js#L69 and the statuscode gets overridden to always return 401.

I rather have it return the error catched here https://github.com/seriousme/fastify-openapi-glue/blob/master/lib/securityHandlers.js#L57 than wrapping it in a general error with wrong code.

Thanks!

**Comment by seriousme** [comment]
Hi,

thanks for asking. 

The security handlers code provides the error and status code to Fastify, and Fastify's default error handler turns this into the reply that you get.

I think that what you want can be rather easily achieved by creating a custom fastify errorHandler.
E.g. something along the lines of:

```javascript
 fastify.setErrorHandler((err, req, reply) => {
    const firstError = err.errors[0];
    reply.code(firstError.statusCode).send(firstError.message);
 });
```

See also: https://github.com/seriousme/fastify-openapi-glue/blob/master/docs/securityHandlers.md

Hope this helps.

Kind regards,
Hans

**Comment by trycoon** [comment]
Thanks!
But I'm using the "fastify-errors-enhanced"-module to format my errors, it already registers an errorHandler inside: https://github.com/ShogunPanda/fastify-http-errors-enhanced/blob/main/src/index.ts#L36
So when the securityhandler rewrites the errors, the response does not follow the OpenAPI-schema expected and a schema-validation error is returned instead.

If it was possible to have several errorhandlers, I could have one after the securityhandler that unwraps the errors and returns it to the one fastify-errors-enhanced expects.

Now I'm more into writing a security-plugin that I register after fastify-openapi-glue, that will do the security checks. The securityhandler in openapi-glue will just decorate the request with the schema-params and always return true.
Or I have to write my own version of "fastify-errors-enhanced"...

**Comment by seriousme** [comment]
Hi,

you could ask `fastify-errors-enhanced` for a preprocessing hook, so you can preprocess errors before they are picked up by `fastify-errors-enhanced`.

We could also look in `fastify-openapi-glue` and if the last error holds a err.statusCode we use your last error instead of the version thats in there now.

Kind regards,
Hans

**Comment by trycoon** [comment]
Good suggestions, I'll look into that.
Thanks!

**Comment by seriousme** [comment]
Turned out to be easier than I thought ;-)

**Comment by seriousme** [comment]
Released as 3.2.0.

**Comment by trycoon** [comment]
Thanks, that will make a big difference for others, I think!
But for me, it doesn't help that much, since the reply for the 401 still does not comply with the 401 schema that Fastify expects:

` unauthorizedSchema:
      type: object
      description: 'Error returned when client does not provide any valid authorization.'
      properties:
        statusCode:
          type: number
          description: 'The error HTTP status code'
          enum: [401]
          example: 401
        error:
          type: string
          description: 'The error HTTP status description'
          enum: ['Unauthorized']
          example: 'Unauthorized'
        message:
          type: string
          description: 'The error message'
          pattern: '.+'
          example: 'Unauthorized.'
        code:
          type: string
          description: 'The error code'
          enum: ['Unauthorized']
          example: 'Unauthorized'
      required: ['statusCode', 'error', 'message']
      additionalProperties: false`
      
   "errors" is not listed above, so a 500-error is returned to the client about the returned object does not comply with above schema.
   I have since then removed fastify-http-errors-enhanced from my project and now have better control of how the reply is sent back.
   
   Thanks for all the help!

**Comment by seriousme** [comment]
Hi,

sorry that it does not seem to work for you yet :-(.

I tried it myself but the default Fastify error handler does not seem to mind that the extra `errors` property exists. It just creates its own thing based on the statusCode, even overriding the error name that the security handlers code has set.

E.g. if the security handlers code ends up with statusCode 451 then in the browser I get:
```json
{"statusCode":451,"error":"Unavailable For Legal Reasons","message":"None of the security schemes (api_key, skipped, failing) successfully authenticated this request."}
```

No complaints about additional properties en no statusCode 500 ;-)

See also https://github.com/seriousme/fastify-openapi-glue/blob/693f37e2f0d57157812f0b9e1ce1b95e94a3976e/test/test-securityHandlers.v3.js#L238-L265

Hope this helps!

Kind regards,
Hans

**Comment by trycoon** [comment]
Hi, and sorry for the late answer, I also have not had the time to put together a example project to demonstrate my use-case/problem. But its not the Fastify and "fastify-openapi-glue" combination that gives me this error, its the combination of "https://github.com/ShogunPanda/fastify-http-errors-enhanced" and "fastify-openapi-glue".

By declaring a "unauthorizedSchema" like this https://github.com/ShogunPanda/http-errors-enhanced/blob/main/src/schemas.ts#L29
And by validating the response pre-serialization https://github.com/ShogunPanda/fastify-http-errors-enhanced/blob/main/src/validation.ts#L224
Fastify-http-errors-enhanced does not like if we send responses back that not follow the registered schema (like the "errors"-property the securityhandler does)

But then again it could just be a misinterpretation of the situation, I may be wrong. :-)

**Comment by seriousme** [comment]
Hi,

I think I got a potential solution for you :-)

`fastify-http-errors-enhanced` is the fastify-specific version of `http-errors-enhanced`.
So this works:

```javascript
import { createError } from 'http-errors-enhanced'
const fastify = Fastify();

fastify.register(fastifyOpenapiGlue, opts);
fastify.setErrorHandler(async (err, req, reply) => {
    reply.code(err.statusCode).send(createError(err.statusCode))
})
fastify.listen({ port: 3000 });
```

Alternatively you could try setting up an extra `context` as the fastify error handlers bubble up. 
See: https://www.fastify.io/docs/latest/Reference/Errors/

Hope this helps !
Hans

**Comment by trycoon** [comment]
Yes, that was how I solved it. I threw fastify-http-errors-enchanced out, and only used http-errors-enhanced together with openapi-glue. And a top-level errorhandler that catches all errors and unwrapps them and send them back according to the schema-specs.

`// Generic error handler, catches all errors thrown, logs them and returns a message and status code to the clients.
function handleErrors(err, req, res) {
  const error = err?.errors?.[0] || err;
  let statusCode = error.statusCode || INTERNAL_SERVER_ERROR;

  // Code outside HTTP range
  if (statusCode < 100 || statusCode > 599) {
    statusCode = INTERNAL_SERVER_ERROR;
  }

  if (statusCode >= 500) {
    logger?.error({
      reqId: error.reqId,
      url: error.url,
      userId: error.userId,
    }, error.loggMessage || error.message);
  } else if (statusCode >= 400) {
    logger?.info({
      reqId: error.reqId,
      url: error.url,
      userId: error.userId,
    }, error.loggMessage || error.message);
  }

  const body = {
    statusCode,
    error: messagesByCodes[statusCode],
    message: error.message,
  };

  res
    .code(statusCode)
    .headers(error.headers ?? {})
    .type('application/json')
    .send(body);
}`

Thanks!
