### ISSUE TITLE
Project lint and code conventions

### ISSUE THREAD

**Issue by GuillaumeDeconinck** [seriousme/fastify-openapi-glue#370]
Hello there 👋 

First, thank you for the work on this module!

I'm planning on contributing on this project for 2-3 things if possible, but from what I see, there aren't yet any linting or code conventions, which increases the friction for starting contributing.

Usually, I have `eslint`, `prettier` and `editorconfig` helping to keep the code base consistent. I was wondering if you agree, and would like, to have these tools added in your project ?

A good enough [article](https://blog.theodo.com/2019/08/empower-your-dev-environment-with-eslint-prettier-and-editorconfig-with-no-conflicts/) on the setup of this. Note that I can do it myself and submit a PR if you want.

Have a nice day!

**Comment by seriousme** [comment]
Hi,

the code conventions have indeed not been enforced. Its more or less prettier style as you already guessed ;-)
I just gave it a quick spin myself but could not get it to work as intended without having to dig deeper into the docs of these tools.
So getting it to work reliably would be much appreciated !

Kind regards,
Hans

**Comment by GuillaumeDeconinck** [comment]
No worries, as you suggest it, I'll open a PR for this ;)
