### ISSUE TITLE
Ability to specify multiple services

### ISSUE THREAD

**Issue by simoami** [seriousme/fastify-openapi-glue#39]
Hello, thanks for this nice plugin! Would it be possible to support passing of an array or map of services? This would allow us to organize functionality into multiple classes that represent different domains. An example would be UserService for user crud operations and, RoleService for the role specific operations...etc. Another example is a shopping cart application with catalog, cart and checkout services. It would be cumbersome to add all in one file.

**Comment by seriousme** [comment]
Hi,

I can see that having to manage big specification files can be cumbersome. 

My first suggestion would be this:

```javascript
const openapiGlue = require("fastify-openapi-glue");

const multiOptions = [
  {
    specification: `${__dirname}/openApi1.json`,
    service: `${__dirname}/service1.js`
  },
  {
    specification: `${__dirname}/openApi2.json`,
    service: `${__dirname}/service2.js`
  }
];

module.exports = async function(fastify, opts) {
  multiOptions.forEach(options => fastify.register(openapiGlue, options));
};

```
This way you can decide for yourself if you want to have single specification file (using the same definition twice) or multiple and a single service definition (same trick) or multiple.
(and as a bonus we don't need to change the interface of the plugin ;-))

Would this work for you ?

Kind regards,
Hans

**Comment by simoami** [comment]
@seriousme Thanks for the suggestions. Yeah I think this works. I'd love to have separate spec files but in my case there's a dependency on the models since it's a hierarchy. But that could be resolved if the definitions can be relocated into a separate file. I'll see if that can be done: multiple specs + multiple services. For now, I'll use the single spec approach with multiple services and see if I can break it down.

**Comment by simoami** [comment]
Oh I can't reuse the same spec, so that option isn't going to work:
```
UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Method 'DELETE' already declared for route '/api/v1/projects/:'
```

**Comment by simoami** [comment]
@seriousme Do you know if $ref can reference external dependencies? I'm trying the following in a swagger 2 specification but no luck:
```
"$ref": "./common.spec.json#/definitions/Project"
```

**Comment by simoami** [comment]
nvm, I added a console.log() to parser.js and got the failing error:
```
ENOENT: no such file or directory, open '/projects/dukketta/data-service/common.spec.json'
```
So I was able to fix the path. I think it would be very helpful if the parser errors are somehow exposed or logged:

*lib/parser.js*
```
    try {
      // parse first, to avoid dereferencing of $ref's
      data = await swp.parse(specification);
      // save the original (with $refs) because swp.validate modifies its input
      this.original = JSON.parse(JSON.stringify(data, null, 2));
      // and validate
      spec = await swp.validate(data);
    } catch (e) {
      console.log(e) <==== I added this to be able to get basic parse errors and rectify the issues
      data = {};
      spec = {};
    }
```

**Comment by seriousme** [comment]
You might want to have  a look at https://swagger.io/docs/specification/using-ref/ 
I have not tried it myself.

Alternatively you could use some templating (e.g. javascript template literals) to generate a single spec out of its sub parts e.g.:

``` javascript

paths: 
    ${roleService}
    ${crudService}

```
And then use a build step to generate a single spec file.

**Comment by simoami** [comment]
Thanks @seriousme. See my last comment ^

**Comment by seriousme** [comment]
Yes, our comments crossed :-)

I have added a console.log statement, see https://github.com/seriousme/fastify-openapi-glue/pull/41

**Comment by simoami** [comment]
Awesome, Thank you! all looks good now. Closing.
