### ISSUE TITLE
"exports" in package.json causing problems with jest testing

### ISSUE THREAD

**Issue by peeveen** [seriousme/fastify-openapi-glue#414]
Hi,
Thanks for this package, it's really useful.
However, I'm having trouble writing jest tests with it.

My code being tested has a simple import:

```
import "fastify-openapi-glue"
```

and works fine when being run outside of the jest test environment.

But when I run jest ...

```
Test suite failed to run
Cannot find module 'fastify-openapi-glue' from 'src/ServiceBuilder.ts'
```

Weirdly, if I change the import to "../node_modules/fastify_openapi_glue/index", it seems to find it, but that's messy, and breaks when my package is used in another project.

I've managed to get it working cleanly by either removing the "exports" section from your package.json, or changing it to:

```
  "exports": {
    ".": "./index.js"
  }
```

**Comment by seriousme** [comment]
Hi,

thanks for asking !
ESM support in Jest is still "experimental", see: https://jestjs.io/docs/ecmascript-modules
This might explain the issue that you see.

Changing the exports section to:
```
"exports": {
    ".": "./index.js"
  }
```
Is basically the equivalent of removing it, as `.` is not a valid qualifier in this section according to: https://nodejs.org/api/packages.html#conditional-exports

Removing the exports section completely is also not a solution as this might break the environment for other users.

So although I would love to help you out, I don't have a good solution now. Maybe the tips on the Jest ESM page can help you out. Worst case scenario you would need something like a `jq` script at the start of your test to edit out the exports section for your  particular use case.

Hope this helps !

Kind regards,
Hans

**Comment by peeveen** [comment]
Yes, I have a simple line of `sed` replacing `"import"` with `"."` for now, and it seems to do the trick.
And I knew ES6 was kinda experimental in Jest, but this is the first package that it has failed with for me.

Just out of curiosity, what is the "exports" section achieving here?
I know the general purpose of the schema, but I would have thought that using a reserved word ("import") would render it useless? I mean, if I try `import import from "fastify-openapi-glue"`, I just get a syntax error, but if I rename it to anything else (for example, "blah") I can then use `import blah from "fastify-openapi-glue"` ... so I was just wondering how this "import" alias could be used?

Thanks

**Comment by seriousme** [comment]
Thanks for the feedback. Good to read you got a working solution for now.

Until ESM support has stabelized in the NodeJS ecosystem we will probably run into more issues like these :-(
I'm trying to balance the needs of various toolchains including ESM, Typescript etc.. while also moving ahead since staying on CJS is also not helping the ecosystem at large :-(

Should you run into other issues, please reach out !

Kind regards,
Hans

**Comment by peeveen** [comment]
Yeah, like I always say about JavaScript, it's pretty good, and it'll be even better when it's finished.

In the meantime, if you feel like making life easier for those of us using your library with `jest` and `babel-jest`, it's a simple thing:

```
  "exports": {
    "import": "./index.js",
    "require": "./index.js"
  }
```

I'll close this anyway.
Thanks for your help.

**Comment by seriousme** [comment]
Hi,

one more question ;-)

Does this work in your setup?
```
  "exports": {
    "import": "./index.js",
    "default": "./index.js"
  }
```
 If so then I think it would be safe for me to add ;-)

Kind regards,
Hans

**Comment by peeveen** [comment]
Hi,
Yes, that works too.
Thanks!

**Comment by seriousme** [comment]
Version 4.0.2 has been published on NPM. See #415

**Comment by peeveen** [comment]
Greatly appreciate this, thanks!
