### ISSUE TITLE
Unable to use require library with issue ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by kcammanabrolu** [seriousme/fastify-openapi-glue#427]
Hi,
    We are typescript project with following typescript compiler options.
{
  "compilerOptions": {
    "esModuleInterop": **true**,
    "module": "**commonjs**",
    "target": "**ES2018**",
    "noImplicitAny": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",
    "strictNullChecks": false,
    "skipLibCheck": true,
    "declaration": true,
    "composite": true,
    "declarationMap": true, // enables importers to jump to source
    "noUnusedLocals": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true
  }
}
After compilation, the target javascript code uses `require` to import the package, but then produces the following error:
![image](https://user-images.githubusercontent.com/17587143/197840532-606b27f5-b93d-4d3e-9fb4-a7d32d4a93bd.png)

The behavior is same even when I use dynamic imports as suggested in the error text.
Seems like the problem is because in the [package.json](https://github.com/seriousme/fastify-openapi-glue/blob/master/package.json#L6) it specifies `type: module`. Is it possible remove this or change it to `commonjs` so that we can use this library. 

Reference: https://nodejs.org/api/packages.html#type

**Comment by seriousme** [comment]
Hi,

thanks for asking.
We can't change the type to `commonjs` as the package is an ESM module and not a CommonJS module ;-)

For configuring Typescript to be able to use ESM see: https://2ality.com/2021/06/typescript-esm-nodejs.html

Basically your TSconfig should look something like this:
```javascript
{
"compilerOptions": {
  "target": "ES2022" /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */,
  "module": "Es2020" /* Specify what module code is generated. */,
  "esModuleInterop": true /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */,
  "forceConsistentCasingInFileNames": true /* Ensure that casing is correct in imports. */,
  "strict": true /* Enable all strict type-checking options. */,
  "skipLibCheck": true /* Skip type checking all .d.ts files. */,
  "moduleResolution": "Node",
  "outDir": "dist",
  "rootDir": "src"
  }
}
```

Hope this helps !

Kind regards,
Hans

I similar issue might be found at: https://github.com/seriousme/fastify-openapi-glue/issues/382
