### ISSUE TITLE
Support for external refs

### ISSUE THREAD

**Issue by GabMus** [seriousme/fastify-openapi-glue#441]
Hi, I'm trying to use this library with an openapi file that has external refs defined as follows: `../mymodels.yaml#/components/schemas/FooBar`

Trying to import this file results in the following error: `Cannot resolve [...], only internal refs are supported.`

Is support for external refs planned? Do you think I have any other alternatives?

Thank you!

**Comment by seriousme** [comment]
Hi,

thanks for asking!


A schema reference always refers a URI (identifier)and not a URL (location)!
see https://spec.openapis.org/oas/v3.1.0#reference-object

This means that a reference is just a reference and will never autoload.

There is however a way to resolve this:
The resolution of references is handled by: https://github.com/seriousme/openapi-schema-validator
This allows for adding additional references, see the example at: https://github.com/seriousme/openapi-schema-validator#addSpecRef

If you pass this result as a an object to OpenApiGlue then it should work.
We could add a way to add these references via the openApiGlue api,however there has been little demand sofar and it would create a more tight dependency on openapi-schema-validator.

Hope this helps.

Kind regards,
Hans

**Comment by GabMus** [comment]
Hi, thanks for the quick response. I believe this could be a workable solution, so I'll be closing this. Thanks again for your work and the support you provide!
