### ISSUE TITLE
Opentelemetry Support

### ISSUE THREAD

**Issue by duffenterprises** [seriousme/fastify-openapi-glue#448]
Any thoughts on how [fastify-opentelemetry](https://github.com/autotelic/fastify-opentelemetry) could be integrated? Fastify-openapi-glue has really jumpstarted my project, but because it's abstracted a lot of boiler plate code, I'm a touch lost.

**Comment by seriousme** [comment]
Hi, 

thanks for asking. Its the first time I looked at fastify-opentelemetry but it think you can apply the example as stated in the readme. I have not tried it myself, but the following should work:

In `index.js` you then put:

```javascript
export default async function (fastify, opts) {
         await fastify.register(openTelemetryPlugin, { wrapRoutes: true })
	fastify.register(openapiGlue, options);
}
``` 

While in `service.js` you put:
```javascript
async addPet(request, reply) {
  const {
      activeSpan,
      tracer,
      // context,
      // extract,
      // inject,
    } = request.openTelemetry()
    // Spans started in a wrapped route will automatically be children of the activeSpan.
    const childSpan = tracer.startSpan(`${activeSpan.name} - child process`)
    // doSomeWork()
    childSpan.end()
}
```

Hope this helps !

Kind regards,
Hans

**Comment by seriousme** [comment]
Hi,

curious to learn weather it works 😁
Please discuss before you spend loads of time on a PR to avoid disappointment 😉

Kind regards,
Hans

**Comment by seriousme** [comment]
Good to see that it worked for you :-)

Any subsequent users can find your experience in this issue, so I don't think we need additional documentation.

So good day to you as well !
Hans
