### ISSUE TITLE
Error in Response Validation Message

### ISSUE THREAD

**Issue by YasarTutuk** [seriousme/fastify-openapi-glue#464]
Hello,

In a swagger 2.0 json api definition the following block is part of the response schema definitions:

```
        "responses": {
          "201": {
            "description": "Created",
            "headers": {
              "some-header": {
                "description": "Description",
                "type": "string"
              }
            }
          },
          "400": {
            "description": "400",
            "schema": {
              "type": "object",
              "properties": {
                "ResultCode": {
                  "title": "CodeType",
                  "example": "42",
                  "type": "string"
                },
                "Annotation": {
                  "title": "TextType",
                  "example": "Response message from application",
                  "type": "string"
                }
              },
              "required": ["ResultCode", "Annotation"]
            }
          }
        } 
```
When the applicaition returns a message that does not fit the schema (here 'Annotation' field is missing) such as : 
```
			reply.code(400).send({
				"ResultCode": "Code Example",
				// "Annotation": "Annotation Example",
			  });

```
The validation fails as expected, however the message is misleading and always displays the first required field when it should be displaying the field that was actually missing:

```
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "\"ResultCode\" is required!"
}
```

**Comment by seriousme** [comment]
Hi,

thanks voor asking!
The error is a

**Comment by YasarTutuk** [comment]
Hey, 

Thanks for the quick response. 've also done that using only fastify and creating a similiar query schema like so:

```
const querySchema = {
  schema: {
    querystring: {
      type: 'object',
      properties: {
        x: {
          type: 'number',
          minimum: -90,
          maximum: 90
        },
        y: {
          type: 'number',
          minimum: -180,
          maximum: 180,
        },
      },
      required: ['lat', 'lon']
    },
    response: {
      200: {
        description: 'Succesful response',
        type: 'object',
        properties: {
          hello: { type: 'string' },
          world: { type: 'string' }
        },
        required: ['hello', 'world']
      }
    }
  }
}
```

calling the endpoint like
http://localhost:8080/api/sample?x=5&y=2 with a valid request and returning:
```
export const sample = async (request: FastifyRequest, reply: FastifyReply) => reply.send({ "hello": "value" });
```
gives the expected response:
```
{"statusCode":500,"error":"Internal Server Error","message":"\"world\" is required!"}
```
the opposite is also true if you change the response to :
```
async (request: FastifyRequest, reply: FastifyReply) => reply.send({ "world": "value" });
```
then
```
{"statusCode":500,"error":"Internal Server Error","message":"\"hello\" is required!"}
```
and if the response is correct of course you don't get a validaiton error:
```
async (request: FastifyRequest, reply: FastifyReply) => reply.send({ "hello": "value", "world": "value" });
```
returns
```
{"hello":"value","world":"value"}
```

So using only fastify, everything is working as expected. This lead me to believe that there might be something wrong with the schema generated by openapi-glue from the swagger 2.0 description.

Kind regards

**Comment by seriousme** [comment]
Interesting :-)

I haven't tried it myself but https://github.com/fastify/fastify-routes (which is a fastify core plugin) should be able to give you information on what is exactly configured in fastify.

Alternatively you relatively easy spy on the routes that are added by the plugin by  looking at: https://github.com/seriousme/fastify-openapi-glue/blob/33bb43c2bc36bd6fec542df10f532bb02b138110/index.js#L105

`routeCfg` holds the config per route that was derived from parsing, just before its being handed to fastify.

Hope this helps and curious to learn what happened !

Kind regards,
Hans

**Comment by YasarTutuk** [comment]
I'll check there and see if I can figure out what's wrong. Thanks for the pointer.

**Comment by seriousme** [comment]
Btw:  in your fastify example you only use `reply.send` whereas  in your first example you specified `reply.code(400).send` , it could be due to different handling of the 400 within fastify ;-)

**Comment by YasarTutuk** [comment]
Hey Hans, 
Response from fastify suggests this is an expcted behaviour and you can see the reason why here: 
https://github.com/fastify/fastify/issues/4592
In short 'Fastify tries to serialize the error, and for some reason, it uses the same FJS function as it used for serializing data' as someone mentioned on the thread.
So they added the behaviour of having the original error in the message as well. But the error will still be a FST_ERR_FAILED_ERROR_SERIALIZATION. So this expected behaviour is not going away anytime soon and it would be nice to have something like you suggested in openapi-glue to see what's going on.
