### ISSUE TITLE
Suggestion about the TS imports errors

### ISSUE THREAD

**Issue by alebas1** [seriousme/fastify-openapi-glue#492]
Hello, there are a lot of GH issues concerning errors about importing this lib in TypeScript projects. Apparently the only solution is to adapt the tsconfig accordingly. 

This can cause issues when using something like NestJS, where a tsconfig is already set.

I don't know how you feel about this project, but this could be a great idea to migrate to ts or to stick to cjs modules, this way, it would make your lib compatible with much more projects.

This is a huge breaking change, i know but probably a good suggestion imo.

We can discuss about this :)

**Comment by seriousme** [comment]
Hi,

thanks for asking!

Do you have a specific case that you want to solve ?
If you have an example that does not work now we can see how we can make it work and maybe solve similar cases at the same time.

Happy to try to see how we can get your case to work!

Kind regards,
Hans
ps. Migrating backwards to CJS is not an option imo as the NodeJS community considers CJS a dying breed ;-)

**Comment by seriousme** [comment]
Btw: did you see: https://stackoverflow.com/questions/74830166/unable-to-import-esm-module-in-nestjs ?
This page describes how to use ESM in nestjs.

**Comment by alebas1** [comment]
I will look into it and provide you a great example ;)

**Comment by alebas1** [comment]
Hello!

I have a repo of my own, I created an issue to explain it a bit more.
see -> https://github.com/alebas1/fastify-api-design-first/issues/8
I reformulated my precise issue when importing your lib. In this precise example I do not use NestJS but the problem is the same.

Imo the fact that i need to import a JS file with its extension is kinda dirty.
From what I've seen, it's the only way to do it :/

Thank you for helping !

**Comment by seriousme** [comment]
Hi,

as you mentioned in https://github.com/alebas1/fastify-api-design-first/issues/8#issuecomment-1609482838: the `.js` extension might look a bit strange but is normal behaviour and the Typescript tooling will work it out.

It's not specific to `fastify-openapi-glue` but a general challenge in Typescript when combined with ESM.
I'm pretty sure the Typescript crew will solve this over time as more package owners move to ESM ;-)

Does this resolve your issue for now ?

Kind regards,
Hans

**Comment by seriousme** [comment]
Ps. I added a note on Typescript to the [notes in README.md](https://github.com/seriousme/fastify-openapi-glue/blob/master/README.md#notes) to help future Typescript users. Thanks again for your question!
