### ISSUE TITLE
Secure select routes

### ISSUE THREAD

**Issue by simo-eskalera** [seriousme/fastify-openapi-glue#51]
Is it possible to configure select routes with `preHandler` methods? This will enable us to secure specific routes that require authenticated users or operations that require specific roles or permissions.

This also leads to the following question. Does `fastify-openapi-glue` play nice with other plugins that hook into the routes lifecycle?

Example:
```
    fastify.route({
      method: 'POST',
      url: '/auth-multiple',
      preHandler: fastify.auth([
        fastify.asyncVerifyJWTandLevel,
        fastify.asyncVerifyUserAndPassword
      ]),
      handler: (req, reply) => {
        req.log.info('Auth route')
        reply.send({ hello: 'world' })
      }
    })
```

**Comment by seriousme** [comment]
Hi,

thanks for asking.

`fastify-openapi-glue` does not contain any mechanism to configure select routes with `preHandler` methods as it just generates routes from a OpenApi specification and there is no way to specify  preHandlers there.

Having said that:  `fastify-openapi-glue`  just generates a fastify plugin and it should be possible to chain plugins. I haven't tried that myself since I have no use case for that, but looking at the docs it should be possible, e.g.: (from https://github.com/fastify/fastify-auth)

```javascript
fastify.addHook('preHandler', fastify.auth([
  fastify.verifyJWTandLevel,
  fastify.verifyUserAndPassword
]))

fastify.route({
  method: 'POST',
  url: '/auth-multiple',
  handler: (req, reply) => {
    req.log.info('Auth route')
    reply.send({ hello: 'world' })
  }
})
```
Translated to `fastify-openapi-glue` something along the lines of:
```javascript
const openapiGlue = require("fastify-openapi-glue");

const options = {
  specification: `${__dirname}/petstore-swagger.v2.json`,
  service: `${__dirname}/service.js`,
  prefix: "v1"
};

fastify.addHook('preHandler', fastify.auth([
  fastify.verifyJWTandLevel,
  fastify.verifyUserAndPassword
]))

fastify.register(openapiGlue, options);
```
should work.

If it turns out that `fastify-openapi-glue` needs some adjustment to play nice with other plugins then I'm open to suggestions.

Kind regards,
Hans

**Comment by simo-eskalera** [comment]
Thanks @seriousme 
This is more of a global approach that you're illustrating. The cases I'm looking to support is where some apis require auth and some don't. Some have custom roles or permissions. For example, the getUsers api requires an admin role whereas getProfile requires user to be authenticated, and getSiteSettings doesn't require auth at all. I think it's also great if `fastify-openapi-glue` doesn't isolate itself so it's either it or the rest. One option I can think of is to check the service handlers. If they are functions, proceed as normal, if they are objects, look for lifecycle methods in the object properties. You could even get away with just merging the object as is on top of the route object.

**Comment by simo-eskalera** [comment]
@seriousme So what I was suggesting is something like this:
in `generateRoutes` in `index.js`:

```
  async function generateRoutes(routesInstance, opts) {
    config.routes.forEach(item => {
      const response = item.schema.response;
      if (response) {
        stripResponseFormats(response);
      }
      const handler = service[item.operationId]
      if (isFunction(handler)) {
        routesInstance.log.debug("service has", item.operationId);
        item.handler = handler;
      } else if ((isObject(handler) && handler.handler) {
        routesInstance.log.debug("service has", item.operationId);
        delete handler.method; // don't override important properties
        delete handler.url; // don't override important properties
        // make it future proof by allowing pass through of props, instead of hand picking specific properties from the object
        Object.assign(item, handler);
      } else {
        item.handler = async (request, reply) => {
          throw new Error(`Operation ${item.operationId} not implemented`);
        };
      }
      routesInstance.route(item);
    });
  }
```

**Comment by seriousme** [comment]
@simo-eskalera thanks for the suggestion.

I have been thinking about it a bit and technically it is perfectly doable. 
The question however is what you gain with it ?

Currently service.js is totally isolated from fastify. You can basically use service.js in any local code and all the "magic" happens in the glue.
If we now extend the interface and introduce fastify specific logic in service.js then basically half of your "specification" sits in the openApi spec and the other half sits in service.js.

Ideally I would rather add the authentication specific stuff to the glue as well, but there we run into the problem that openApi specs can define many more variants than fastify is able to handle out of the box.

Another option is to expand the generator in such a way that it generates fastify code (routes and schema as code, not just a on-the-fly plug-in) to which you can then add all the custom handling. That way the whole "specification" is then in the code.

What do you think ?

Kind regards,
Hans

**Comment by seriousme** [comment]
Closing this one for now. Feel free to reopen if you want to continue the discussion.

**Comment by simo-eskalera** [comment]
@seriousme Sorry I forgot to follow up. I think we're good for now. I can always add class method decorators for auth, or inline checks in the handler. I currently do this:

```
exports.list = async (req, rep) => {
  requireAuthenticated(req)
  ...
}
```

**Comment by seriousme** [comment]
@simo-eskalera 
I think I see what you mean and to be honest I'm a bit torn between the two sides.
On one hand its tempting to expand service.js with fastify specific stuff e.g.:
```javascript
exports.getUsers = {
   preValidation: () => {...} // Fetch user roles
   preHandler: () => {...} // Run my auth validation here
   handler: (req, rep) => { ... }
}
```
On the other hand this "leaks" the abstraction of fastify into service.js that I'm trying to avoid.

**Comment by simo-eskalera** [comment]
@seriousme, thanks for re-opening.
> this "leaks" the abstraction of fastify into service.js that I'm trying to avoid.

I didn't think you need to touch service.js to support this. The change that I shared above only needs to go in the root `index.js` which already has references to fastify anyways. Ref: https://github.com/seriousme/fastify-openapi-glue/blob/master/index.js#L72

**Comment by seriousme** [comment]
@simo-eskalera 
The "leak" here is not that I need to change `service.js`.  `service.js` is not part of the plugin but supplied by the user (in this case you ;-)). 

So far the user could use more or less any framework that supports `(req,res)=>{...}` without knowing the intimate details of fastify. E.g. the user can use any test framework to do unit testing on service.js without using fastify. 

If we allow the user to specify fastify details like:
```javascript
exports.getUsers = {
   preValidation: () => {...} // Fetch user roles
   preHandler: () => {...} // Run my auth validation here
   handler: (req, rep) => { ... }
}
```
Then this abstraction between the plugin and service.js shifts. Suddenly the user needs to know that the hook ```preValidation``` is executed before ```preHandler``` and a unit test for service.js needs to include fastify or else the logic won't fly. So that's why I'm hesitative to make this shift.

**Comment by simo-eskalera** [comment]
@seriousme 
Got it. The preValidation and preHandler were just given as examples, it could be any other parameter. you don't break the abstraction at all if the extra parameters are simply forwarded as is. For example, in a plugin architecture, a user would supply plugin specific configuration, but the plugin manager doesn't need to know what they are. the system would simply just forward those to the appropriate plugin. What I consider hardcoding is if you had to explicitly reference any of the fastify parameters in the code, which is not the case here. Your plugin would still be transparent to them. You also don't want your plugin to introduce unnecessary limitations.

Here's what I mean in a simplified illustration. Forgive the over simplification. I just want to illustrate that the other props can totally be ignored by your plugin and get passed on as is.

<img width="902" alt="Screen Shot 2019-10-17 at 11 43 46 PM" src="https://user-images.githubusercontent.com/49319958/67064359-433c5200-f138-11e9-96f3-b699235a922a.png">

**Comment by seriousme** [comment]
@simo-eskalera 
I can see that the plugin can forward all unknown properties to its descendants. The question is though whether this should affect the interface between the plug-in and service.js as this means that the author of any service.js needs to understand fastify details to be able to use this.

Anyways: just to see how things would work I created a branch called [fastify-pass-through](https://github.com/seriousme/fastify-openapi-glue/tree/fastify-pass-through) with your suggested changes in there. All works like a charm for the current testcases, but I'm still looking for a elementary test case that ensures that the new functionality works. (I also want to stay at 100% test coverage ;-))  Ideally something like the [test for missing authorization headers](https://github.com/seriousme/fastify-openapi-glue/blob/fastify-pass-through/test/test-plugin.v3.js#L129)

Do you have a simple example of such a hook that I can easily test and also presents a bit of a logical use case ?

**Comment by seriousme** [comment]
@simo-eskalera 
As I don't have any example for testing I'm going to close this issue for now.
