### ISSUE TITLE
Compression doesn't work

### ISSUE THREAD

**Issue by vitaliypavlenko** [seriousme/fastify-openapi-glue#595]
If you have compression registered and enabled in fastily and this package used - compression doesn't work.
This is how it is used:
`await fastify.register(
        import('@fastify/compress'),
        {  global: true },
      );
const openapiGlue = await import('fastify-openapi-glue');
    const glueOptions = {
      specification: mergedApiDefinition,
      operationResolver: this._operationResolver.bind(this),
    };

    await fastify.register(openapiGlue, glueOptions);`
    If compression headers are sent - result is missing body, but it is present without headers:
    `curl -H 'Accept-Encoding:gzip, deflate, br' -X POST http://localhost:3000/`

**Comment by seriousme** [comment]
Hi,

thanks for asking!

`fastify-openapi-glue` is a plugin for fastify,  and the only thing it does is create a config for fastify that:
a) binds routes like '/v2/pet' to a handler
b) configures security handling and parameter validation for these routes

If the `@fastify/compress` plugin does not work then the most likely cause has to be [encapsulation](https://fastify.dev/docs/latest/Reference/Encapsulation/ )

Can you please try if you can create a simple working example with `compress` and a simple  plugin like:
```javascript
async function plugin (fastify, opts) {
  fastify.get('/', async (req, reply) => {
    return { hello: 'world' }
  })
}
```

If that works then `fastify-openapi-glue` should work as well, if not then maybe the fastify team can help out.

Kind regards,
Hans
