### ISSUE TITLE
Type generation for handlers

### ISSUE THREAD

**Issue by jacobinu** [seriousme/fastify-openapi-glue#598]
Hello! I can echo past comments how useful this project is for enabling a schema first approach, so thanks to all the contributors. I've thinking about improving the DX with this plugin with handler type generation so that we can have [type checking on incoming request data and outgoing type code/data](https://fastify.dev/docs/latest/Reference/TypeScript/#using-generics).

<img width="439" alt="image" src="https://github.com/user-attachments/assets/f5145f16-f1b6-4927-8015-164e14494f82">

I've been following the project https://github.com/hey-api/openapi-ts for client code generation and I noticed that the type generator have a [close enough shape](https://heyapi.vercel.app/openapi-ts/output.html#typescript-interfaces) to the required inputs to Fastify type generics. With some changes to the generator in the openapi-ts project and the use of the [Fastify type RouteHandler](https://github.com/fastify/fastify/blob/6cbfe0559b9996ca1d6d306ea506bd31210951ae/types/route.d.ts#L168) I was able to generate route types mapped to operator id's like shown above.

In the end I hoped to
1. Write the API spec
2. Generate client code and Fastify route handler typing
3. Implement Fastify handlers with type checking
4. Attach the handlers to the glue plugin

I am interested to see if there is any interest in this approach. Thanks!

**Comment by seriousme** [comment]
Hi,

thanks for asking!
The subject has come up before (see e.g. https://github.com/seriousme/fastify-openapi-glue/issues/581, https://github.com/seriousme/fastify-openapi-glue/issues/201).

The challenge is to add robust JSONschema to Typescript types transformation without needing to rely on a large third party dependency tree, as relying on large dependency trees comes with its own challenges. 

My current plan is to wait for type support in Node to mature  (currently experimental see: https://socket.dev/blog/node-js-adds-experimental-support-for-typescript)  as I expect that to accelerate type handling in Node.

The generator can already support multiple template sets (see https://github.com/seriousme/fastify-openapi-glue/tree/master/lib/templates)  so adding a Typescript template should be fairly easy once the dust around Types settles. 

Kind regards,
Hans

**Comment by jcx0** [comment]
Hi Hans, thanks for the reply. I do agree that relying on the dependency would be a lot of work. I am curious what challenges we still face for Type generation. 

#201 mentions issues of libraries, but it being 3 years later I'm not sure which ones we still face.

#581 mentions "no stable way to generate Typescript types from OpenApi types". Should there be non native TS types I know that [openapi-typescript project](https://github.com/openapi-ts/openapi-typescript/tree/main/packages/openapi-typescript) handles that with [user written transforms](https://openapi-ts.dev/node#transform-posttransform).

As to "how to template the types", we could create a operationId to Fastify RouteHandler map.
```
import {type RouteHander} from "fastify";

type Handlers = {
  createUser: RouteHandler <{
    Body: NewUser;
    Reply: {
      201: User;
      400: Error;
      401: Error;
      409: Error;
      500: unknown;
    };
  }>;
  getUser: {
    Reply: {
      200: User;
      400: Error;
      401: Error;
      500: unknown;
    };
  }>;
};

const handlers: Handlers = {
  createUser: async function (request, reply) {}
  getUser: async function (request, reply) {}
}

fastify.register(glue, {
  specification: "api.yaml",
  serviceHandlers: handlers,
  prefix: "v1",
});

**Comment by seriousme** [comment]
Hi Jacob,

the challenge is not in the fastify types like Fastify's  Request and Response objects as those are easy to add and also quite stable. What does pose a challenge however are the TypeScript types for the parameters coming from the openApi spec.
In your example the `User` and `Error` types.

People can put simple stuff in there like:

https://github.com/seriousme/fastify-openapi-glue/blob/6d3605ed914f0ca7c79736d572a57da1250e59bd/examples/petstore/petstore-openapi.v3.json#L900-L915

Or more complex stuff like: 
https://github.com/seriousme/fastify-openapi-glue/blob/6d3605ed914f0ca7c79736d572a57da1250e59bd/examples/petstore/petstore-openapi.v3.json#L917-L962

And I have seen way more complex stuff while running real world tests at:  https://github.com/seriousme/openapi-schema-validator/tree/master/test/realworld

I'm not keen on just doing the simple stuff (ints/strings/etc) and leaving the more complex stuff (date-time/etc) for users to fix themselves. The libraries discussed in #201 still seem to have quite some challenges around edge cases.

So we need something that can handle arbitrarily complex JSON schema with some confidence that it does the right thing.

If you know  of such tools (that do not have a huge dependency tree)  then I'm more than happy to investigate.

Its relatively easy to add another set of templates to the generator if you are interested in experimenting.

Kind regards,
Hans

**Comment by jcx0** [comment]
I as understand type formats like date-time well defined in json under their type specific keyword (strings, numbers, array) and it would be enough to leave them as their primitives. For example, if we are using date-time I think it would be enough to leave it as a string as users of an API will understand it is a formatted string from reading the JSON Schema spec. I do see how type like Schema Composition and Conditional Subschemas could be difficult. I do admit I have not used OpenAPI in production and have rarely encountered complex schemas. Perhaps an iterative approach could be taken to tackle the low handle types and leave the difficult/complex types to added later by future contributors. I did ask the maintainer of the openapi-ts project to spin off their generator and they seem open to the idea https://github.com/hey-api/openapi-ts/issues/838. Perhaps there could be a greater collaborative effort to tackle these edge case types.

Thank you for your time Hans!

**Comment by seriousme** [comment]
Jacob,

thanks for this discussion. If openapi-ts splits off their generator that might be a candidate indeed.

Kind regards,
Hans

**Comment by mrlubos** [comment]
Hey @seriousme, I am only starting to wrap my head around this issue to estimate the amount of work this would require. Any sources you can point me to would be appreciated.

Aside, I see https://www.npmjs.com/package/fastify-openapi-glue downloads went from ~250k/wk in February to ~73k/wk today. Is there an alternative solution people migrated to? Do you know what caused the decline?

**Comment by seriousme** [comment]
Hi @mrlubos ,

Thanks for asking:  

We need to come up with a robust solution that converts JSONschema (see https://json-schema.org/specification) to Typescript Types, including https://www.typescriptlang.org/docs/handbook/2/objects.html, https://www.typescriptlang.org/docs/handbook/enums.html etc 

Just useing "any" (see https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#any) is an easy solution, but does not really help the user much.

So we need to be able to convert schema definitions like `Pet` above (and more complex ones) reliably in to typescript types so that you can look at `req.query` and see the Typescript definition of the query parameters for this route.

Hope this explains it a bit.

I just noticed that [@fastify/type-provider-json-schema-to-ts](https://github.com/fastify/fastify-type-provider-json-schema-to-ts) exists, this might solve the issue, but I'd like to see some solid test cases around that.

Kind regards,
Hans

**Comment by seriousme** [comment]
@mrlubos 

As to the number of downloads:
I don't care too much for the number of downloads as I'm not in opensource for money or fame but just for the fun of it.
Then again I was also suprised by the large increase in downloads some months ago and did some research on the subject. Looking at https://www.npmjs.com/package/fastify-openapi-glue?activeTab=dependents there are about 10 projects depending on my module. Looking at each of them it became clear that the spike was caused by https://www.npmjs.com/package/@platformatic/composer. If you look at the download graphs they almost overlap.

Does this answer your question?

Kind regards,
Hans

**Comment by mrlubos** [comment]
It answers it more than enough, thank you for the additional context!
