### ISSUE TITLE
[Question] - How to add a request hook that is performed after "security handler"

### ISSUE THREAD

**Issue by JayPe69** [seriousme/fastify-openapi-glue#619]
Hello,

I would like to add stuff on the request object by using fastify hook / decorator.
But I want the openapiglue security handler to be "played" before applying the hook decorator.

Do you have any idea to impement it ?

Thanks a lot.

**Comment by seriousme** [comment]
Hi,

thanks for asking.
The security handler runs on Fastify's [preHandler](https://fastify.dev/docs/latest/Reference/Hooks/#prehandler) hook.
So if you want to run custom code then you have 3 options:
1) add the custom code at the start of your service handler
2) add the custom code at the end of your security handler

However this might not work if you have standard Fastify middleware.
In that case you need to add your own hook by adding a `prehandler` hook using [onRoute](https://fastify.dev/docs/latest/Reference/Hooks/#onroute) . Hooks will be executed in the order that they were added.

Hope this helps,
Hans
