### ISSUE TITLE
How to handle multiple security check for a specific path (security 1 or security 2)

### ISSUE THREAD

**Issue by JayPe69** [seriousme/fastify-openapi-glue#625]
Hello,

In the open api schema it's possible to define multiple security checks for a path :   

https://swagger.io/docs/specification/v3_0/authentication/
```
security: # A OR B
  - A
  - B
```

Then in openApiGlue, I'll have to add both method in the security handler class

```
export class security {
    A(req: FastifyRequest, reply: FastifyReply) {
        
    }

    B(req: FastifyRequest, reply: FastifyReply) {
        
    }
}
```

If the check in A throws an exception, then the response will be a 401.
The system won't go to B to see if it's OK.

Is there any tips to make sure that the system check A or B and if one them is OK, return a 20X and not 401 ?

For example :  
- If A is waiting for a Bearer Token
- if B is waiting for a Basic Auth

If I call the endpoint with a Basic Auth, then A will throw an error : Bearer Token not found  

I know that a solution will be to merge both and make one that check both possibilities.

Thanks

**Comment by JayPe69** [comment]
Thanks for your answer.
This is what I've seen in your documentation.

The thing is that if A throws an exception, then you'll never go through B.

Does it mean instead of throwing exception, I should return True or False ?
In that case how can I specify error message ?

**Comment by seriousme** [comment]
See the tests at:

https://github.com/seriousme/fastify-openapi-glue/blob/master/test/test-securityHandlers.js

these use the security handlers specified in: 

https://github.com/seriousme/fastify-openapi-glue/blob/master/test/security.js

Hope this helps,
Hans

**Comment by seriousme** [comment]
Glad to read it worked!
