### ISSUE TITLE
Revisiting Fastify server binding to "this"

### ISSUE THREAD

**Issue by jacobinu** [seriousme/fastify-openapi-glue#630]
We should have the option to bind "this" to the Fastify server.

#169 discuses why this is not currently the case, but I believe what we pass to serviceHandlers should be the Fastify RouteHandler/controllers. We can instead attach our services to the Fastify server like so

```ts
const plugin: FastifyPluginAsync<ServicesOptions> = async function (
  fastify,
  options
) {
  const { providers } = options;
  const user = new providers.UserService({ db });
  fastify.decorate("userService", service);
};

```

and use the service in our handler like such

```ts
async getUserById(request, reply) {
  const { userId } = request;
  const result = await this.userService.getUserById({
    userId,
  });
  return reply.code(200).send(result);
}
```

Thus we still maintain the requirement that "you should be able to test your service without Fastify".

I've been working on [creating the RouteHandler type generator](https://github.com/hey-api/openapi-ts/issues/1215#issuecomment-2481735587) to get type checking on the RouteHandler params with use of the official `RouteHandler` Fastify type. This type supports accessing the Fastify instance with "this" (which is why I'm asking for the option to allow the Fastify instance to "this"). With codegen from OpenAPI spec we can also quickly test our Fastify server against the spec. There is an example in the type generator link.

**Comment by seriousme** [comment]
Hi,

thanks for asking.
`this` is now bound to the object that holds the `serviceHandlers` which makes it possible to have things like:

```javascript
export class Service {
	constructor(userService) {
		this.userService = userService;
	}

	async getUserById(request) {
		const { userId } = request;
		const result = await this.userService.getUserById({
			userId,
		});
		return result;
	}
}
```

Which can then be called by using:

```javascript
const { providers } = options;
const userService = new providers.UserService({ db });
const serviceHandlers = new Service(userService);

const pluginOptions = {
	specification: localFile("./petstore-openapi.v3.json"),
	serviceHandlers,
	prefix: "v2",
};

export default async function (fastify, opts) {
	fastify.register(openapiGlue, pluginOptions);
}

export const options = {
	ajv: {
		customOptions: {
			strict: false,
		},
	},
};
```

this way you can use `service.js` with any webserver or testing framework as long as `request` provides a `userid` property.
If `this` would refer to fastify then I would need to decorate the route in fastify and for testing I would need another way to bind the userService to `this`.

Changing the default operationResolver to bind to fastify instead would break other peoples code. However, if you really want to have a reference to fastify in your service handlers then you could:

1.  add a `setFastify()` method to the `Service` class, that sets `this.fastify` to fastify
2.  use a custom operationResolver which allows you to bind your service handlers to anything you like

As to the Typescript types: I'm not a guru on Fastify types, but if I read this correctly:

> The interfaces Body, Querystring, Params and Headers will be passed down through the route method into the route method handler request instance and the Reply interface to the reply instance.

https://fastify.dev/docs/latest/Reference/TypeScript/#typescript

it should be possible to create a custom type that defines request and reply out of the fastify type generics. Without having to use the full routeHandler type. And even with the full routeHandler type it should be possible to `Pick` only the stuff that you need and leave the Fastify `this` out of the equation.

For now I have kept Typescript out of the equation wrt fastify-openapi-glue as the Type generation and the testability of generated Typescript is quite of a hassle, but now that NodeJS is offering more native support for Typescript there might be a future where  fastify-openapi-glue  can treat typescript as first class citizen.

Kind regards,
Hans
ps. if you want a full fledged platform to develop API's then have a look at:  https://docs.platformatic.dev/

**Comment by jacobinu** [comment]
Hi Hans,

I do see the value of services being able to have interoperability across frameworks. However, I am curious how you handle sending responses with error codes e.g. `reply.code(409).send('error')`. The API for other frameworks might differ. For example, express looks like this `res.status(500).send('Something broke!')`.

Regardless, thank you for pointing out the operationResolver option. I missed this detail and I believe satisfies my request.

I looked into platformatic and it doesn't seem to support OpenAPI to TypeScript types. Type generation and testability of said type generation is indeed a hassle which is why I've help develop it as plugin on top of an existing generator. I think we are already there wrt to being able to treat TypeScript as a first class citizen in the spec first world.

**Comment by seriousme** [comment]
Hi Jacob,

great to read you found a solution that works for you.
I noticed tonight that you can also use `reply.server` to get access to the server instance.
https://fastify.dev/docs/latest/Reference/Reply/#server

Kind regards,
Hans
