### ISSUE TITLE
'this' is losing it's scope in service.js

### ISSUE THREAD

**Issue by schulz3000** [seriousme/fastify-openapi-glue#73]
if I call a sub method in my service.js file from the method that was requested by fastify it could not be found.

Sample:
```
async addPet(req, reply) {
    console.log("addPet", req.params);
    this.createPet(req.query.name);
    return { key: "value" };
  }

createPet(name) {
console.log(`Pet ${name} created`);
}
```

Getting a HTTP 500 error that says this.createPet method not found. Looks like 'this' is losing it's scope.

**Comment by seriousme** [comment]
Published as part of version 1.5.2 on NPM
