### ISSUE TITLE
Support multipart/form-data requests

### ISSUE THREAD

**Issue by batodev** [seriousme/fastify-openapi-glue#80]
Hi,

it seems that fastify-openapi-glue doesn't support multipart/form-data requests at all. I notice some warnings at service startup
```
body type: multipart/form-data found
```
and there's no input validation.
If I call my service with multipart/form-data body it returns 415 with `FST_ERR_CTP_INVALID_MEDIA_TYPE` error message.

**Comment by seriousme** [comment]
Hi,

fastify-openapi-glue  only supports the bodypart types that Fastify supports and Fastify does not support multipart/form-data  out of the box.

There is however a [multipart/form-data plugin for fastify](https://github.com/fastify/fastify-multipart) that you could try. You would need to register both openapi-glue and multiPart on the same fastify instance. Fastify-openapi-glue will still report the:
```
body type: multipart/form-data found
```
On startup as it does not have a way to detect that you have a plugin loaded for that specific body type.

I haven't tried it myself so I'd be happy to hear if that works !

Kind regards,
Hans

**Comment by batodev** [comment]
I tried, now it returns Bad Request
```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "body should be object"
}
```
and it lets me send Json body even if multipart/form-data is the only allowed content-type in Swagger spec.

Thank you for your help!
Tommaso

**Comment by seriousme** [comment]
From:  https://github.com/fastify/fastify-multipart 

`You can also use all the parsed HTTP request parameters to the body:`
```javascript
const options = {
  addToBody: true,
  sharedSchemaId: 'MultipartFileType', // Optional shared schema id
  onFile: (fieldName, stream, filename, encoding, mimetype, body) => {
    // Manage the file stream like you need
    // By default the data will be added in a Buffer
    // Be careful to accumulate the file in memory!
    // It is MANDATORY consume the stream, otherwise the response will not be processed!
    // The body parameter is the object that will be added to the request
    stream.resume()
  },
  limit: { /*...*/ } // You can the limit options in any case
}

fastify.register(require('fastify-multipart'), options)
```
That should solve your empty body problem.

As for blocking normal JSON payloads you could either look at `req.headers` in your `service.js` or you could try to [modify the application/json parser ](https://www.fastify.io/docs/latest/ContentTypeParser/#content-type-parser) so that it always returns an error.

Kind regards,
Hans

**Comment by batodev** [comment]
Thank you again, I will try! :)

Tommaso
