### ISSUE TITLE
The 1.7.1 tag doesn't support fastify 3

### ISSUE THREAD

**Issue by jamoy** [seriousme/fastify-openapi-glue#93]
current workaround is to install the dependency via the github handle

```
npm install seriousme/fastify-openapi-glue
```

using this on fastify 3 will invoke an error on `instance.setSchemaCompiler` on index.js

besides the above. love the library! thank you for your work!

**Comment by seriousme** [comment]
You are quick :-) 

Fastify 3 is only a few days old and I already fixed Master thats why `npm install seriousme/fastify-openapi-glue` works.
Just released 2.0.0 as the change is not compatible with fastify 2.x.y

Kind regards,
Hans
